### PR TITLE
Updated Userfeaturefile

### PR DESCRIPTION
**Pull request by yashashree07**
removed comment from user feature file for Maker2 test data

### CODE REVIEW

**Review by pranjal-13 — COMMENTED** [review]
@yashashree07 Add one more Maker in User feature Modify tag

**Review by yashashree07 — COMMENTED** [review]
@pranjal-13 updated feature file added comment to Checker13

**Review by pranjal-13 — CHANGES_REQUESTED** [review]
@yashashree07 Delete one user from Add tag

**Review by yashashree07 — COMMENTED** [review]
@pranjal-13  deleted user #1

**Review by pranjal-13 — APPROVED** [review]
Ok

**Pull request merged**
